name: Development workflow

on: 
  workflow_dispatch:
    inputs:
      username:
        description: 'Enter your name'
        required: true
      environment:
        description: 'Select environment'
        required: true
        default: 'staging'

jobs:
  read-json:
    runs-on: ubuntu-latest
    steps:
      - name: Display User Inputs
        run: |
          echo "User Name: ${{ github.event.inputs.username }}"
          echo "Selected Environment: ${{ github.event.inputs.environment }}"
          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read project.json
        run: |
          project_name=$(jq -r '.name' project.json)
          main_file=$(jq -r '.main' project.json)
          echo "Project Name: $project_name"
          echo "Main File: $main_file"
