name: Development workflow
on:
  push:  # Runs whenever a commit is pushed to the repository
    branches:
      - main            #workflow_dispatch:

#inputs:
#      DeploymentVersion:
#        description: 'Enter the version Number to deploy'
#        required: true
#      environment:
 #       description: 'Select environment'
#        required: true
  #      default: 'staging'

jobs:
  read-json:
    runs-on: ubuntu-latest
    steps:
      - name: Display User Inputs
        run: |
          #echo "DeploymentVersion: ${{ github.event.inputs.DeploymentVersion }}"
          #echo "Selected Environment: ${{ github.event.inputs.environment }}"
          
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read project.json
        run: |
          project_name=$(jq -r '.name' project.json)
          project_version=$(jq -r '.projectVersion' project.json)
          main_file=$(jq -r '.main' project.json)
          echo "Project Name: $project_name"
          echo "Project Version: $project_version"
          echo "Main File: $main_file"
          
      - name: Validate environment variable
        run: |
          if [[ $project_version !=  "1.0.1" ]] ; then
            echo "Invalid DeploymentVersion value: "
            exit 1
          fi
           echo "Validation successful!" 
